def receta_ceviche_peruano():
    print("Receta de Ceviche Peruano")
    print()
    print("Ingredientes:")
    print("- 1 kg de filete de pescado blanco fresco (corvina, lenguado, o similar)")
    print("- 10 limones grandes (jugo recién exprimido)")
    print("- 1 cebolla roja, cortada en pluma fina")
    print("- 1 ají limo o ají amarillo, picado en rodajas finas")
    print("- 2 dientes de ajo, picados finamente")
    print("- 1 manojo de culantro (cilantro), picado fino")
    print("- Sal al gusto")
    print("- Pimienta al gusto")
    print("- 1 trozo de camote cocido (para acompañar)")
    print("- 1 choclo desgranado y cocido (para acompañar)")
    print()
    print("Instrucciones:")
    print("1. Corta el pescado en cubos pequeños y colócalos en un bol grande.")
    print("2. Añade sal, pimienta, ajo picado y el ají limo o ají amarillo al gusto. Mezcla suavemente.")
    print("3. Vierte el jugo de los limones sobre el pescado hasta cubrirlo. Mezcla bien.")
    print("4. Deja reposar por 10-15 minutos, hasta que el pescado tome un color blanco opaco (se 'cocine' con el jugo de limón).")
    print("5. Añade la cebolla roja en pluma y el cilantro picado. Mezcla suavemente.")
    print("6. Sirve acompañado de camote y choclo cocidos.")
    print()
    print("¡Listo! Ya tienes un delicioso ceviche peruano.")

